name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: all_cn_cidr
          path: all_cn_cidr.*
